# Runs the full training pipeline for the chess AI model, including data loading, model initialization, training loop, and checkpointing and optional data creation and preparation steps.
import os
import datetime
import generator
import data_preparer
import trainer
import tester

# ----------------------
# PIPELINE CONFIGURATION
# ----------------------

# Puzzle generation configuration (generator.py)
GENERATE_DATASET = False  # Set to True to generate a dataset of puzzles with solutions
GEN_DATASET_SIZE = 100000  # Number of puzzles to generate for the dataset
GEN_BLANKS = range(40, 51)  # Range of blanks, keep under 64 (MIN to MAX+1)
GEN_MAX_SOLUTIONS = 4  # Maximum number of solutions allowed for each generated puzzle (1 for unique solution)
GEN_DATESTAMP = datetime.datetime.now().strftime("%Y%m%d%H%M")
GEN_DATASET_UID = f"{GEN_DATASET_SIZE}_{min(GEN_BLANKS)}-{max(GEN_BLANKS)}_{GEN_MAX_SOLUTIONS}_{GEN_DATESTAMP}"  # Unique identifier for the generated dataset based on parameters and timestamp

# Data preparation configuration (data_preparer.py)
PREPARE_DATASET = False  # Set to True to prepare the dataset (one-hot encoding and splitting)
TEST_MODE = False  # Set to True to run a test of the one-hot encoding function
PREP_DATASET_UID = "100000_40-50_4_202606141914"  # Unique identifier for the prepared dataset "1000_10-40_1_202606131802")
TARGET_RAW_DATASET = f"data/chess_puzzle_dataset_{GEN_DATASET_UID if GENERATE_DATASET else PREP_DATASET_UID}.json"  # Path to the dataset generated by generator.py
PERFORM_SPLIT = True  # Set to True to split the dataset into training and validation sets
TARGET_SPLIT_RATIO = 0.9  # Ratio for splitting the dataset into training and validation sets

# Training configuration and setup (trainer.py)
# Note: Ensure PREP_DATASET_UID is set to the target training dataset's UID if not generating a new dataset.
TRAIN_MODEL = True  # Set to True to train the model, False to skip training and use existing checkpoints
CHECKPOINT_PATH = "models/chess_model_checkpoint_latest.pth"
TARGET_TRAINING_DATASET = TARGET_RAW_DATASET.replace("data/chess_puzzle_dataset", "data/encoded/split/chess_puzzle_dataset_one_hot_encoded").replace(".json", "_train.json") # Path to the one-hot encoded training dataset generated by data_preparer.py
LEARNING_RATE = 0.001
ESTOP_PATIENCE = 10
TRAINING_EPOCHS = 100
SCHEDULER_FACTOR = 0.1  # Factor by which the learning rate will be reduced. new_lr = lr * factor
SCHEDULER_PATIENCE = 5  # Number of epochs with no improvement after which learning rate will be reduced.

# Testing configuration (tester.py)
# Note: Ensure PREP_DATASET_UID is set to the target test dataset's UID if not generating a new dataset.
TEST_MODEL = True  # Set to True to test the model, False to skip testing
HEADLESS_MODE = True  # Set to True to run without rendering (for faster testing), False to see the step-by-step visualization
TARGET_TEST_DATASET = TARGET_TRAINING_DATASET.replace("_train.json", "_test.json")  # Path to the one-hot encoded test dataset generated by data_preparer.py
TARGET_TEST_MODEL = "models/chess_model_best.pth"  # Path to the best trained model weights

# The following is a universal test position for the solvers.
UNIVERSAL_TEST_PUZZLE = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

UNIVERSAL_TEST_SOLUTION = [
  [5, 3, 4, 6, 7, 8, 9, 1, 2],
  [6, 7, 2, 1, 9, 5, 3, 4, 8],
  [1, 9, 8, 3, 4, 2, 5, 6, 7],
  [8, 5, 9, 7, 6, 1, 4, 2, 3],
  [4, 2, 6, 8, 5, 3, 7, 9, 1],
  [7, 1, 3, 9, 2, 4, 8, 5, 6],
  [9, 6, 1, 5, 3, 7, 2, 8, 4],
  [2, 8, 7, 4, 1, 9, 6, 3, 5],
  [3, 4, 5, 2, 8, 6, 1, 7, 9]
]


def run_pipeline():
    # Step 1: Generate the dataset (if not already generated)
    if GENERATE_DATASET:
        print("Step 1: Generating dataset...")
        generator.main(GENERATE_DATASET, GEN_DATASET_SIZE, GEN_BLANKS, GEN_MAX_SOLUTIONS, GEN_DATESTAMP)
    else:
        print("Step 1: Skipping dataset generation (already generated)")

    # Step 2: Prepare the dataset (one-hot encoding and splitting)
    if PREPARE_DATASET:
        print("Step 2: Preparing dataset...")
        data_preparer.main(TEST_MODE, TARGET_RAW_DATASET, PERFORM_SPLIT, TARGET_SPLIT_RATIO)
    else:
        print("Step 2: Skipping dataset preparation (already prepared)")

    # Step 3: Train the model
    if TRAIN_MODEL:
        print("Step 3: Training model...")
        trainer.main(CHECKPOINT_PATH, TARGET_TRAINING_DATASET, LEARNING_RATE, ESTOP_PATIENCE, TRAINING_EPOCHS, SCHEDULER_FACTOR, SCHEDULER_PATIENCE)  # This will train the model and save checkpoints
    else:
        print("Step 3: Skipping model training (using existing checkpoints)")

    # Step 4: Test the model
    if TEST_MODEL:    
        print("Step 4: Testing model...")
        tester.main(HEADLESS_MODE, TARGET_TEST_DATASET, TARGET_TEST_MODEL)
    else:
        print("Step 4: Skipping model testing")

def main():
    # Allow globals modification
    global GENERATE_DATASET, PREPARE_DATASET, TRAIN_MODEL, TEST_MODEL

    # Additional prechecks will be added here
    # Checks must be ordered from last step to first to ensure hierarchy of dependencies.
    
    # Prevent overwriting existing datasets.
    if PREPARE_DATASET and os.path.exists(TARGET_TRAINING_DATASET):
        # Don't overwrite a prepared dataset.
        print(f"Warning: Prepared training dataset already exists at {TARGET_TRAINING_DATASET}. Skipping preparation to avoid overwriting.")
        PREPARE_DATASET = False  # Set to False to skip preparation since the prepared dataset already exists

    if GENERATE_DATASET and os.path.exists(TARGET_RAW_DATASET):
        # Don't overwrite a raw dataset.
        print(f"Warning: Raw dataset already exists at {TARGET_RAW_DATASET}. Skipping generation to avoid overwriting.")
        GENERATE_DATASET = False  # Set to False to skip generation since the dataset already exists
    
    # Prevent moving forward without required datasets.
    if TEST_MODEL and not os.path.exists(TARGET_TEST_MODEL) and not TRAIN_MODEL:
        # No model checkpoint to test with.
        print(f"Warning: Test model checkpoint not found at {TARGET_TEST_MODEL}. Enabling training to create it.")
        TRAIN_MODEL = True  # Set to True to enable training since the test model checkpoint doesn't exist and is needed for testing

    if TRAIN_MODEL and not os.path.exists(TARGET_TRAINING_DATASET) and not PREPARE_DATASET:
        # No training dataset to train from.
        print(f"Warning: Prepared training dataset not found at {TARGET_TRAINING_DATASET}. Enabling dataset preparation to create it.")
        PREPARE_DATASET = True  # Set to True to enable preparation since the training dataset is needed for training and doesn't exist
    
    if PREPARE_DATASET and not os.path.exists(TARGET_RAW_DATASET) and not GENERATE_DATASET:
        # No raw dataset to prepare from.
        print(f"Warning: Raw dataset not found at {TARGET_RAW_DATASET}. Enabling dataset generation to create it.")
        GENERATE_DATASET = True  # Set to True to enable generation since the raw dataset is needed for preparation and doesn't exist
    

    run_pipeline()

if __name__ == "__main__":
    main()