# chess AI Step-by-Step Visual Tester
import os
import json
import datetime
import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
import torch.nn.functional as F
# Import the model architecture from the trainer file
from trainer import V7P3RMindCNN

HEADLESS_MODE = True  # Set to True to run without rendering (for faster testing), False to see the step-by-step visualization
TARGET_TEST_DATASET = "data/encoded/split/chess_puzzle_dataset_beginner_202606170841_test.json"  # Path to the one-hot encoded test dataset generated by data_preparer.py
TARGET_TEST_MODEL = "models/chess_model_best.pth"  # Path to the trained model weights

# Simulation Control Globals
sim_speed = 0.5
sim_running = True
force_quit = False

def load_latest_model(model_path="models/chess_model_best.pth"):
    """Loads the trained weights into the architecture."""
    model = V7P3RMindCNN()
    if os.path.exists(model_path):
        checkpoint = torch.load(model_path, weights_only=False)
        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
        else:
            model.load_state_dict(checkpoint)
        print(f"Loaded model weights from {model_path}")
    else:
        print(f"Warning: {model_path} not found. Using untrained weights.")
    model.eval()
    return model

def render_board(ax, board, original_mask, title=""):
    """Draws a clean, readable chess grid with distinct colors for guesses."""
    ax.clear()
    ax.set_title(title, fontsize=14, pad=10)
    
    # Draw standard chess grid lines
    for i in range(10):
        lw = 2.5 if i % 3 == 0 else 0.5
        ax.axhline(i, color='black', linewidth=lw)
        ax.axvline(i, color='black', linewidth=lw)
        
    # Populate the numbers
    for r in range(9):
        for c in range(9):
            val = board[r, c]
            if val != 0:
                color = 'black' if original_mask[r, c] else 'blue'
                ax.text(c + 0.5, 8.5 - r, str(val), 
                        va='center', ha='center', 
                        fontsize=18, fontweight='bold', color=color)
                
    ax.set_xlim(0, 9)
    ax.set_ylim(0, 9)
    ax.axis('off')

def check_violations(board):
    """Calculates structural infractions on a potentially finished board."""
    row_violations = 0
    col_violations = 0
    block_violations = 0
    
    for i in range(9):
        # Rows
        row = board[i, :]
        row_counts = np.bincount(row[row != 0], minlength=10)
        row_violations += np.sum(row_counts > 1)
        
        # Cols
        col = board[:, i]
        col_counts = np.bincount(col[col != 0], minlength=10)
        col_violations += np.sum(col_counts > 1)
        
    # Blocks
    for r in range(0, 9, 3):
        for c in range(0, 9, 3):
            block = board[r:r+3, c:c+3].flatten()
            block_counts = np.bincount(block[block != 0], minlength=10)
            block_violations += np.sum(block_counts > 1)
            
    return int(row_violations), int(col_violations), int(block_violations)

def run_step_by_step_test(headless_mode_active, model, puzzle_one_hot, solution_raw, puzzle_id=0):
    """
    Simulates the model 'working out' the puzzle dynamically, 
    selecting the highest confidence cell across the entire board at each step.
    Includes confidence tracking and simulation controls.
    """
    global sim_speed, sim_running, force_quit
    
    # Reset per-puzzle state
    sim_running = True
    
    # 1. Convert one-hot puzzle input back to a standard 9x9 matrix for tracking
    # CRITICAL FIX (2026-06-13): argmax on dim=-1 (the one-hot encoding dimension), not dim=0
    current_board = puzzle_one_hot[0].argmax(dim=-1).cpu().numpy()  # Shape: (9, 9, 10) -> (9, 9)
    
    # 2. Create permanent masks
    original_mask = (current_board != 0)
    
    # Confidence logging
    confidence_history = []
    # Detailed step logging
    step_details = []
    
    fig = None
    ax_board = None
    ax_graph = None
    
    if not headless_mode_active:
        # Set up the visualization
        fig, (ax_board, ax_graph) = plt.subplots(1, 2, figsize=(14, 6))
        plt.subplots_adjust(bottom=0.2)
        plt.ion() 
        
        # --- UI BUTTONS ---
        # Store references in a list to prevent garbage collection
        fig._buttons = []
        
        ax_stop = plt.axes([0.1, 0.05, 0.1, 0.075])
        ax_slower = plt.axes([0.25, 0.05, 0.1, 0.075])
        ax_faster = plt.axes([0.4, 0.05, 0.1, 0.075])
        ax_snapshot = plt.axes([0.55, 0.05, 0.1, 0.075])
        ax_quit = plt.axes([0.8, 0.05, 0.1, 0.075])

        btn_stop = Button(ax_stop, 'Pause/Play')
        btn_slower = Button(ax_slower, 'Slower')
        btn_faster = Button(ax_faster, 'Faster')
        btn_snapshot = Button(ax_snapshot, 'Snapshot')
        btn_quit = Button(ax_quit, 'Kill Test', color='red', hovercolor='orange')
        
        fig._buttons.extend([btn_stop, btn_slower, btn_faster, btn_snapshot, btn_quit])

        def toggle_pause(event):
            global sim_running
            sim_running = not sim_running
            print(f"Simulation {'Resumed' if sim_running else 'Paused'}")

        def speed_down(event):
            global sim_speed
            sim_speed = min(2.0, sim_speed + 0.2)
            print(f"Delay increased to {sim_speed:.1f}s")

        def speed_up(event):
            global sim_speed
            sim_speed = max(0.01, sim_speed - 0.2)
            print(f"Delay decreased to {sim_speed:.1f}s")

        def take_snapshot(event):
            # Create the analysis/snapshots folder if it doesn't exist
            snapshot_dir = "analysis/snapshots"
            if not os.path.exists(snapshot_dir):
                os.makedirs(snapshot_dir)
            
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
            filename = f"{snapshot_dir}/chess_inference_{timestamp}.png"
            plt.savefig(filename)
            print(f"Snapshot saved to {filename}")

        def quit_sim(event):
            global force_quit
            force_quit = True
            plt.close()

        btn_stop.on_clicked(toggle_pause)
        btn_slower.on_clicked(speed_down)
        btn_faster.on_clicked(speed_up)
        btn_snapshot.on_clicked(take_snapshot)
        btn_quit.on_clicked(quit_sim)
        
        # Initial render
        render_board(ax_board, current_board, original_mask, title="Initial Puzzle")
        ax_graph.set_title("Inference Confidence per Step")
        ax_graph.set_xlabel("Solve Step")
        ax_graph.set_ylabel("Confidence (%)")
        ax_graph.set_ylim(0, 105)
        plt.draw()
        plt.pause(1.0)
    
    # Count how many total blanks we need to solve
    total_blanks = np.sum(current_board == 0)
    step = 0
    while step < total_blanks:
        if force_quit:
            return False, [], {}
            
        if not sim_running:
            plt.pause(0.1)
            continue
            
        # Re-encode current_board into the 4D (Batch, Channel, H, W) format the CNN expects
        board_tensor = torch.tensor(current_board, dtype=torch.long)
        one_hot = F.one_hot(board_tensor, num_classes=10).float()
        inputs = one_hot.permute(2, 0, 1).unsqueeze(0)
        
        with torch.no_grad():
            outputs = model(inputs)
            
        best_confidence = -1.0
        best_cell = None
        best_digit = None
        
        # Scan through the board to find the highest-confidence valid digit placement
        for r in range(9):
            for c in range(9):
                if current_board[r, c] == 0:
                    # Calculate softmax over ALL 10 channels first to preserve true probability scaling
                    full_probs = F.softmax(outputs[0, :, r, c], dim=0).cpu().numpy()
                    
                    # Slice out ONLY the actual digit channels (indices 1-9)
                    digit_probs = full_probs[1:]  # Length 9, representing digits 1-9
                    
                    # Find the best digit option from the sliced array
                    best_digit_idx = np.argmax(digit_probs)
                    confidence = digit_probs[best_digit_idx]
                    actual_digit = best_digit_idx + 1  # Map index 0-8 back to digits 1-9
                    
                    # Track the single highest confidence placement across the entire board
                    if confidence > best_confidence:
                        best_confidence = confidence
                        best_cell = (r, c)
                        best_digit = actual_digit
        
        if best_cell is not None:
            r, c = best_cell
            current_board[r, c] = best_digit
            confidence_history.append(float(best_confidence * 100))
            
            # Log refined step details
            step_details.append({
                "step": step,
                "cell": [int(r), int(c)],
                "digit": int(best_digit),
                "confidence": float(best_confidence)
            })
            
            if not headless_mode_active:
                title_text = f"Step {step+1}: Filled ({r},{c}) with {best_digit}\nConfidence: {best_confidence * 100:.1f}% (Delay: {sim_speed:.1f}s)"
                render_board(ax_board, current_board, original_mask, title=title_text)
                ax_graph.plot(range(1, len(confidence_history) + 1), confidence_history, 'bo-')
                plt.draw()
                plt.pause(sim_speed)
        
        step += 1
        
    # Final verification against ground truth
    is_correct = np.array_equal(current_board, solution_raw)
    
    # Structural Analysis for Logs
    v_row, v_col, v_block = check_violations(current_board)
    
    # Detailed fingerprint for this specific puzzle
    fingerprint = {
        "puzzle_id": puzzle_id,
        "is_correct": bool(is_correct),
        "violations": {"row": v_row, "col": v_col, "block": v_block},
        "initial_board": puzzle_one_hot[0].argmax(dim=-1).cpu().numpy().tolist(),
        "final_board": current_board.tolist(),
        "ground_truth": solution_raw.tolist(),
        "steps": step_details
    }
    
    if not headless_mode_active and not force_quit:
        plt.ioff()
        final_title = "SUCCESS: Solved Perfectly!" if is_correct else "FAILURE: Logical Mistake!"
        render_board(ax_board, current_board, original_mask, title=final_title)
        plt.draw()
        
        # Keep window open if paused at the end, or wait a minimum of 2 seconds
        # This allows the user to take a snapshot of the finished board.
        print("Puzzle complete. Waiting for user to unpause or 2s timeout...")
        wait_time = 0
        while (not sim_running or wait_time < 2.0) and not force_quit:
            plt.pause(0.1)
            wait_time += 0.1
            
        plt.close(fig)
    
    return is_correct, confidence_history, fingerprint

def main(headless_mode=HEADLESS_MODE, target_test_dataset=TARGET_TEST_DATASET, target_test_model=TARGET_TEST_MODEL):
    # 1. Load the target model
    model = load_latest_model(target_test_model)
    
    # 2. Load the test dataset
    with open(target_test_dataset, 'r') as f:
        test_data = json.load(f)

    print(f"Loaded {len(test_data)} test puzzles from {target_test_dataset}.")
    
    correct_count = 0
    total_samples = 10 if not headless_mode else len(test_data)
    
    if not headless_mode:
        print(f"Running visual tests for {total_samples} samples...")
    else:
        print(f"Running headless batch evaluation on {total_samples} samples...")

    # 3. Iterate through the test puzzles
    detailed_logs = []
    for i in range(total_samples):
        puzzle = test_data[i]
        puzzle_one_hot = torch.tensor(puzzle['puzzle'], dtype=torch.float32).unsqueeze(0)
        solution_raw = np.array(puzzle['solution']).argmax(axis=-1)
        
        is_correct, conf_history, fingerprint = run_step_by_step_test(headless_mode, model, puzzle_one_hot, solution_raw, puzzle_id=i)
        detailed_logs.append(fingerprint)
        
        if force_quit:
            print("\nTest terminated by user.")
            break
            
        if is_correct:
            correct_count += 1
            
        if headless_mode and (i + 1) % 10 == 0:
            print(f"Processed {i+1}/{total_samples}... Current Accuracy: {(correct_count/(i+1))*100:.2f}%")

    print(f"\nFinal Test Results:")
    print(f"Total Puzzles: {total_samples}")
    print(f"Perfectly Solved: {correct_count}")
    accuracy = (correct_count/total_samples)*100
    print(f"Accuracy: {accuracy:.2f}%")

    # --- LOGGING RESULTS ---
    dataset_name = os.path.basename(target_test_dataset).replace(".json", "")
    log_dir = "analysis/logs"
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
        
    log_timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_dir, f"results_{dataset_name}.log")
    
    with open(log_file, 'a') as f:  # Append mode to keep history for the same dataset
        f.write("-" * 40 + "\n")
        f.write(f"Test Run: {log_timestamp}\n")
        f.write(f"Model: {target_test_model}\n")
        f.write(f"Total Puzzles: {total_samples}\n")
        f.write(f"Perfectly Solved: {correct_count}\n")
        f.write(f"Accuracy: {accuracy:.2f}%\n")
        f.write("-" * 40 + "\n\n")
    
    # --- JSON DATA LOGGING (For Notebook Analysis) ---
    json_log_file = os.path.join(log_dir, f"failed_puzzles_analysis_{dataset_name}.json")
    with open(json_log_file, 'w') as f:
        json.dump(detailed_logs, f, indent=2)
    
    print(f"Detailed analysis data saved to {json_log_file}")
    print(f"Results archived to {log_file}")

if __name__ == "__main__":
    main()