#!/usr/bin/env python3
"""
Train Move Ordering Network with V7P3R Evaluation Imitation

This script trains the move ordering AI to mimic V7P3R's evaluation brain by:
1. Extracting 58 evaluation features from positions (V7P3RAIEvaluator)
2. Getting V7P3R's actual evaluation scores (V7P3RRewardCalculator)
3. Training AI to predict scores from features (imitation learning)

Result: AI that makes evaluation decisions similar to V7P3R but 10-100x faster.

Author: Pat Snyder
Created: 2026-05-03 (V7P3R Imitation Training v1.0)
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

import argparse
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import chess
import json
from tqdm import tqdm
from typing import List, Dict, Tuple
from dataclasses import dataclass

from evaluation.v7p3r_ai_evaluator import V7P3RAIEvaluator, EvaluationFeatures
from training.v7p3r_reward_system import V7P3RRewardCalculator, FeatureImitationLoss
from models.move_ordering_network import MoveOrderingNetwork


@dataclass
class TrainingConfig:
    """Training configuration for V7P3R imitation learning"""
    # V7P3R engine settings
    v7p3r_engine_path: str
    v7p3r_search_depth: int = 3
    
    # Training data
    puzzle_path: str
    max_positions: int = 10000
    
    # Model settings
    model_path: str = None
    hidden_size: int = 512
    num_layers: int = 4
    
    # Training hyperparameters
    batch_size: int = 64
    learning_rate: float = 0.0001
    num_epochs: int = 10
    weight_decay: float = 0.0001
    
    # Loss weights
    eval_loss_weight: float = 1.0
    ranking_loss_weight: float = 0.5
    feature_loss_weight: float = 0.3
    
    # Device
    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'
    
    # Output
    checkpoint_dir: str = 'checkpoints/imitation'
    log_interval: int = 10


class V7P3RImitationDataset(Dataset):
    """
    PyTorch dataset for V7P3R imitation learning.
    
    Each sample contains:
    - Position features (58-dimensional vector from V7P3RAIEvaluator)
    - V7P3R's evaluation score (ground truth)
    - Move quality label
    - Position metadata
    """
    
    def __init__(self, training_data_path: str):
        """
        Load training data generated by V7P3RRewardCalculator.
        
        Args:
            training_data_path: Path to JSON dataset
        """
        with open(training_data_path, 'r') as f:
            data = json.load(f)
        
        self.metadata = data['metadata']
        self.samples = data['training_data']
        
        print(f"Loaded {len(self.samples)} training samples")
        print(f"Feature count: {self.metadata['feature_count']}")
        print(f"V7P3R version: {self.metadata['v7p3r_version']}")
    
    def __len__(self) -> int:
        return len(self.samples)
    
    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        sample = self.samples[idx]
        
        return {
            'features': torch.tensor(sample['features'], dtype=torch.float32),
            'v7p3r_score': torch.tensor([sample['v7p3r_score']], dtype=torch.float32),
            'move_quality': torch.tensor([sample['move_quality']], dtype=torch.float32),
            'move_rank': sample['move_rank'],
            'is_tactical': sample['is_tactical'],
            'is_endgame': sample['is_endgame']
        }


class V7P3REvaluationPredictor(nn.Module):
    """
    Neural network that predicts V7P3R-style evaluations from features.
    
    Architecture:
    - Input: 58-dimensional feature vector (from V7P3RAIEvaluator)
    - Hidden: Multi-layer transformer with self-attention
    - Output: Evaluation score (centipawns) + feature importance weights
    
    This network learns to:
    1. Weight features like V7P3R does implicitly
    2. Predict evaluation scores matching V7P3R
    3. Generalize to new positions using learned feature weights
    """
    
    def __init__(self, feature_dim: int = 58, hidden_size: int = 512, num_layers: int = 4):
        super().__init__()
        
        self.feature_dim = feature_dim
        
        # Feature embedding
        self.feature_encoder = nn.Sequential(
            nn.Linear(feature_dim, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.ReLU(),
            nn.Dropout(0.1)
        )
        
        # Transformer layers for feature interaction
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_size,
            nhead=8,
            dim_feedforward=hidden_size * 4,
            dropout=0.1,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        
        # Evaluation head
        self.eval_head = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_size // 2, 1)
        )
        
        # Feature importance head (learns which features matter most)
        self.importance_head = nn.Sequential(
            nn.Linear(hidden_size, feature_dim),
            nn.Sigmoid()  # Output feature weights [0, 1]
        )
    
    def forward(self, features: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Forward pass.
        
        Args:
            features: [batch, 58] - Feature vectors
            
        Returns:
            eval_scores: [batch, 1] - Predicted evaluation scores
            feature_weights: [batch, 58] - Learned feature importance weights
            weighted_features: [batch, 58] - Features weighted by importance
        """
        # Encode features
        x = self.feature_encoder(features)  # [batch, hidden]
        
        # Add sequence dimension for transformer
        x = x.unsqueeze(1)  # [batch, 1, hidden]
        
        # Transform features
        x = self.transformer(x)  # [batch, 1, hidden]
        x = x.squeeze(1)  # [batch, hidden]
        
        # Predict evaluation
        eval_scores = self.eval_head(x)  # [batch, 1]
        
        # Calculate feature importance
        feature_weights = self.importance_head(x)  # [batch, 58]
        
        # Apply feature weighting
        weighted_features = features * feature_weights
        
        return eval_scores, feature_weights, weighted_features


def create_v7p3r_dataset(config: TrainingConfig) -> str:
    """
    Create training dataset by running V7P3R on puzzle positions.
    
    Args:
        config: Training configuration
        
    Returns:
        Path to generated dataset file
    """
    print("\n" + "="*80)
    print("STEP 1: Creating V7P3R Imitation Dataset")
    print("="*80)
    
    # Initialize evaluator and reward calculator
    evaluator = V7P3RAIEvaluator()
    reward_calc = V7P3RRewardCalculator(
        v7p3r_engine_path=config.v7p3r_engine_path,
        feature_evaluator=evaluator,
        search_depth=config.v7p3r_search_depth
    )
    
    # Load puzzle positions
    print(f"\nLoading puzzles from: {config.puzzle_path}")
    with open(config.puzzle_path, 'r') as f:
        puzzle_data = json.load(f)
    
    # Extract FEN positions
    positions = []
    for puzzle in puzzle_data.get('puzzles', puzzle_data.get('training_data', []))[:config.max_positions]:
        if 'fen' in puzzle:
            positions.append(puzzle['fen'])
        elif 'position_fen' in puzzle:
            positions.append(puzzle['position_fen'])
    
    print(f"Loaded {len(positions)} positions")
    
    # Create output dataset
    os.makedirs(config.checkpoint_dir, exist_ok=True)
    dataset_path = os.path.join(config.checkpoint_dir, 'v7p3r_imitation_dataset.json')
    
    # Generate training data
    reward_calc.create_training_dataset(
        positions=positions,
        output_path=dataset_path,
        max_positions=config.max_positions
    )
    
    return dataset_path


def train_epoch(model: V7P3REvaluationPredictor,
                dataloader: DataLoader,
                criterion: FeatureImitationLoss,
                optimizer: optim.Optimizer,
                device: str,
                epoch: int,
                log_interval: int) -> Dict[str, float]:
    """Train one epoch"""
    model.train()
    
    total_loss = 0.0
    eval_loss_sum = 0.0
    ranking_loss_sum = 0.0
    feature_loss_sum = 0.0
    
    pbar = tqdm(dataloader, desc=f"Epoch {epoch}")
    
    for batch_idx, batch in enumerate(pbar):
        features = batch['features'].to(device)
        v7p3r_scores = batch['v7p3r_score'].to(device)
        move_qualities = batch['move_quality'].to(device)
        
        # Forward pass
        ai_predictions, feature_weights, weighted_features = model(features)
        
        # Calculate loss
        loss, loss_components = criterion(
            ai_predictions=ai_predictions,
            v7p3r_scores=v7p3r_scores,
            ai_features=weighted_features,
            v7p3r_features=features,  # Target is V7P3R's features
            move_qualities=move_qualities
        )
        
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        
        # Accumulate losses
        total_loss += loss.item()
        eval_loss_sum += loss_components['evaluation']
        ranking_loss_sum += loss_components['ranking']
        feature_loss_sum += loss_components['feature_consistency']
        
        # Update progress bar
        if batch_idx % log_interval == 0:
            pbar.set_postfix({
                'loss': f"{loss.item():.4f}",
                'eval': f"{loss_components['evaluation']:.4f}",
                'rank': f"{loss_components['ranking']:.4f}",
                'feat': f"{loss_components['feature_consistency']:.4f}"
            })
    
    num_batches = len(dataloader)
    return {
        'total_loss': total_loss / num_batches,
        'eval_loss': eval_loss_sum / num_batches,
        'ranking_loss': ranking_loss_sum / num_batches,
        'feature_loss': feature_loss_sum / num_batches
    }


def validate(model: V7P3REvaluationPredictor,
            dataloader: DataLoader,
            device: str) -> Dict[str, float]:
    """Validate model"""
    model.eval()
    
    total_error = 0.0
    total_abs_error = 0.0
    num_samples = 0
    
    with torch.no_grad():
        for batch in dataloader:
            features = batch['features'].to(device)
            v7p3r_scores = batch['v7p3r_score'].to(device)
            
            ai_predictions, _, _ = model(features)
            
            # Calculate errors
            error = ai_predictions - v7p3r_scores
            total_error += error.sum().item()
            total_abs_error += error.abs().sum().item()
            num_samples += features.size(0)
    
    return {
        'mean_error': total_error / num_samples,
        'mean_abs_error': total_abs_error / num_samples
    }


def main():
    parser = argparse.ArgumentParser(description="Train AI to imitate V7P3R evaluation")
    
    # V7P3R engine
    parser.add_argument('--v7p3r-engine', type=str, required=True,
                       help='Path to V7P3R UCI engine (v18.3 recommended)')
    parser.add_argument('--v7p3r-depth', type=int, default=3,
                       help='Search depth for V7P3R evaluation')
    
    # Training data
    parser.add_argument('--puzzle-path', type=str, required=True,
                       help='Path to puzzle dataset JSON')
    parser.add_argument('--max-positions', type=int, default=10000,
                       help='Maximum positions to use for training')
    parser.add_argument('--skip-dataset-creation', action='store_true',
                       help='Skip dataset creation (use existing dataset)')
    
    # Model
    parser.add_argument('--hidden-size', type=int, default=512,
                       help='Hidden layer size')
    parser.add_argument('--num-layers', type=int, default=4,
                       help='Number of transformer layers')
    
    # Training
    parser.add_argument('--batch-size', type=int, default=64,
                       help='Batch size')
    parser.add_argument('--learning-rate', type=float, default=0.0001,
                       help='Learning rate')
    parser.add_argument('--num-epochs', type=int, default=10,
                       help='Number of training epochs')
    parser.add_argument('--weight-decay', type=float, default=0.0001,
                       help='L2 regularization')
    
    # Output
    parser.add_argument('--checkpoint-dir', type=str, default='checkpoints/imitation',
                       help='Directory to save checkpoints')
    
    args = parser.parse_args()
    
    # Create config
    config = TrainingConfig(
        v7p3r_engine_path=args.v7p3r_engine,
        v7p3r_search_depth=args.v7p3r_depth,
        puzzle_path=args.puzzle_path,
        max_positions=args.max_positions,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        num_epochs=args.num_epochs,
        weight_decay=args.weight_decay,
        checkpoint_dir=args.checkpoint_dir
    )
    
    print("\n" + "="*80)
    print("V7P3R Evaluation Imitation Training")
    print("="*80)
    print(f"Device: {config.device}")
    print(f"V7P3R Engine: {config.v7p3r_engine_path}")
    print(f"Search Depth: {config.v7p3r_search_depth}")
    print(f"Max Positions: {config.max_positions}")
    print(f"Batch Size: {config.batch_size}")
    print(f"Learning Rate: {config.learning_rate}")
    print(f"Num Epochs: {config.num_epochs}")
    
    # Step 1: Create dataset (if needed)
    dataset_path = os.path.join(config.checkpoint_dir, 'v7p3r_imitation_dataset.json')
    
    if not args.skip_dataset_creation or not os.path.exists(dataset_path):
        dataset_path = create_v7p3r_dataset(config)
    else:
        print(f"\nUsing existing dataset: {dataset_path}")
    
    # Step 2: Load dataset
    print("\n" + "="*80)
    print("STEP 2: Loading Dataset")
    print("="*80)
    
    full_dataset = V7P3RImitationDataset(dataset_path)
    
    # Split into train/val (90/10)
    train_size = int(0.9 * len(full_dataset))
    val_size = len(full_dataset) - train_size
    
    train_dataset, val_dataset = torch.utils.data.random_split(
        full_dataset, [train_size, val_size]
    )
    
    train_loader = DataLoader(
        train_dataset,
        batch_size=config.batch_size,
        shuffle=True,
        num_workers=4
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=4
    )
    
    print(f"Train samples: {len(train_dataset)}")
    print(f"Val samples: {len(val_dataset)}")
    
    # Step 3: Initialize model
    print("\n" + "="*80)
    print("STEP 3: Initializing Model")
    print("="*80)
    
    model = V7P3REvaluationPredictor(
        feature_dim=58,
        hidden_size=config.hidden_size,
        num_layers=config.num_layers
    ).to(config.device)
    
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    
    print(f"Model parameters: {total_params:,}")
    print(f"Trainable parameters: {trainable_params:,}")
    
    # Step 4: Setup training
    criterion = FeatureImitationLoss(
        eval_weight=config.eval_loss_weight,
        ranking_weight=config.ranking_loss_weight,
        feature_weight=config.feature_loss_weight
    )
    
    optimizer = optim.AdamW(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay
    )
    
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='min',
        factor=0.5,
        patience=2,
        verbose=True
    )
    
    # Step 5: Train
    print("\n" + "="*80)
    print("STEP 4: Training")
    print("="*80)
    
    best_val_error = float('inf')
    
    for epoch in range(1, config.num_epochs + 1):
        # Train
        train_metrics = train_epoch(
            model=model,
            dataloader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            device=config.device,
            epoch=epoch,
            log_interval=config.log_interval
        )
        
        # Validate
        val_metrics = validate(
            model=model,
            dataloader=val_loader,
            device=config.device
        )
        
        # Print metrics
        print(f"\nEpoch {epoch}/{config.num_epochs}")
        print(f"  Train Loss: {train_metrics['total_loss']:.4f}")
        print(f"    - Eval Loss: {train_metrics['eval_loss']:.4f}")
        print(f"    - Ranking Loss: {train_metrics['ranking_loss']:.4f}")
        print(f"    - Feature Loss: {train_metrics['feature_loss']:.4f}")
        print(f"  Val Mean Abs Error: {val_metrics['mean_abs_error']:.2f} cp")
        
        # Update learning rate
        scheduler.step(val_metrics['mean_abs_error'])
        
        # Save checkpoint
        if val_metrics['mean_abs_error'] < best_val_error:
            best_val_error = val_metrics['mean_abs_error']
            
            checkpoint_path = os.path.join(
                config.checkpoint_dir,
                f'v7p3r_evaluator_best.pt'
            )
            
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_error': best_val_error,
                'config': config
            }, checkpoint_path)
            
            print(f"  ✓ Saved best model (val_error: {best_val_error:.2f} cp)")
    
    print("\n" + "="*80)
    print("Training Complete!")
    print("="*80)
    print(f"Best validation error: {best_val_error:.2f} cp")
    print(f"Model saved to: {config.checkpoint_dir}")


if __name__ == "__main__":
    main()
